config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'schedules#index'
  resources :schedules, only: [:index, :new, :create, :edit, :update, :destroy]
  get '/schedules/index2', to: 'schedules#index2', as: 'index2_schedules'
  get '/schedules/index3', to: 'schedules#index3', as: 'index3_schedules'
  resources :categories, only: [:index, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true

  belongs_to :user
  has_many :schedules, dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  with_options presence: true do
    validates :title, :start_time
  end
  validates :category_id, numericality: { greater_than: 0, message: 'please select' }

  validate :start_time_before_end_time, :end_time_after_start_time

  def start_time_before_end_time  #start_timeがend_timeより後の日付だとバツ
    if start_time && end_time && start_time > end_time
      errors.add(:start_time, "must be before end time")
    end
  end

  def end_time_after_start_time   #end_timeがstart_timeより前の日付だとバツ
    if start_time && end_time && end_time < start_time
      errors.add(:end_time, "must be after start time")
    end
  end

  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :schedules, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to index2_schedules_path
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      render json: { category: @category }
    else
      render json: { errors: @category.errors.full_messages }, status: :unprocessable_entity
    end
  end
  
  
  def destroy
    @category = Category.find(params[:id])
    return unless current_user.id == @category.user.id
    @category.destroy
  end
  

  private

  def category_params
    params.require(:category).permit(:id,:name).merge(user_id: current_user.id)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update, :destroy]
  before_action :set_category, only: [:new, :create, :edit, :update]
  before_action :move_to_index, only: [:edit]

  def index
    @schedules = current_user.schedules.includes(:category)

    respond_to do |format|
      format.html
      format.json { render json: @schedules }
    end
  end
  
  def index2
    @schedules_by_month = current_user.schedules.order(start_time: :asc).group_by { |s| s.start_time.strftime('%Y-%m') }
    @category = Category.new
  end

  def index3
    @schedules = current_user.schedules.includes(:category)

    respond_to do |format|
      format.html
      format.json { render json: @schedules }
    end
  end

  def new
    @schedule = Schedule.new
    @category = Category.new

  end
  
  def create
    @schedule = Schedule.create(schedule_params)
    if @schedule.save
      redirect_to root_path
    else
      render :new
    end
  end

def edit
end

def update
  if @schedule.update(schedule_params)
    redirect_to root_path
  else
    render :edit
  end
end

def destroy
  return unless current_user.id == @schedule.user.id
  @schedule.destroy
  redirect_to root_path
end


  private

  def schedule_params
    params.require(:schedule).permit(:title, :start_time, :end_time, :description, :category_id).merge(user_id: current_user.id)
  end

  def set_schedule
    @schedule = Schedule.includes(:user).find(params[:id])
  end

  def set_category
    @categories = current_user.categories
  end
  
  def move_to_index
    return unless current_user.id != @schedule.user.id

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/categories/index.html.erb
<div class="category-ind">
  <div id="new-form-container">
    <%= form_with model: @category, local: true, class: 'category-form', id: "cat-form"  do |f| %>
      <%= f.hidden_field :id %>
      <%= f.text_field :name %>
      <%= f.submit '追加', class: 'cat-btn', id: "add-submit" %>
    <% end %>
  </div>

<!--<div id="edit-form-container" style="display: none;">
    <%= form_with model: nil, url: '', remote: true, id: 'edit-form' do |f| %>
      <%= f.hidden_field :id %>
      <%= f.text_field :name %>
      <%= f.submit '更新', class: 'cat-btn', id: "up-submit" %>
    <% end %>
  </div>
-->

  <div class="category-list">
    <% @categories.each do |category| %>
      <%= category.name %>
      <%= link_to '編集', '#', class: 'edit-link', data: { category_id: category.id } %>
      <%= link_to '削除', category_path(category), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'delete-link' %>
      <br>
    <% end %>
  </div>
</div>


<!--
<script>
  // JavaScriptのコードをここに記述する
  $(document).on('click', '.edit-link', function (e) {
    e.preventDefault();
    $('#new-form-container').hide();
    $('#edit-form-container').show();
    const link = $(this);
    const categoryId = link.data('category-id');
    const editUrl = '/categories/' + categoryId;


    $('#up-submit').off('click').on('click', function (e) {
      e.preventDefault();
      const formData = $('#edit-form').serialize();
      const updatedFormData = `${formData}&category[id]=${categoryId}`;

      $.ajax({
        url: editUrl,
        method: 'PATCH',
        data: updatedFormData,
        success: function (response) {
        },
        error: function (xhr, status, error) {
        }
      });
    });
  });
</script>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('favicon.ico') %>
    <title>Chroniquill</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Slackside+One&family=Zen+Kaku+Gothic+Antique:wght@300;400;500;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/schedules/edit.erb
<%= render 'shared/header' %>

<div class="new-main">
  <%= form_with model: @schedule, class: "schedule-form", local: true, id: "schedule-form" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.date_field :start_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :end_time %>
      <%= f.date_field :end_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= link_to "Delete", schedule_path(@schedule.id), method: :delete, class:"btn-destroy" %>
      <%= f.submit "Write", class: "btn-write" %>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/schedules/edit.html.erb
<div class="new-main">
  <%= image_tag "form-up.png", class: "form-flame" %>
  <%= form_with model: @schedule, class: "schedule-form", local: true, id: "schedule-form" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :start_time, class: "form-label" %>
      <%= f.date_field :start_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :end_time, class: "form-label" %>
      <%= f.date_field :end_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :category_id, class: "form-label" %>
      <%= f.collection_select :category_id, @categories, :id, :name, {}, { class: "form-select" } %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= link_to "Delete", schedule_path(@schedule.id), method: :delete, class:"btn-destroy" %>
      <%= f.submit "Write", class: "btn-write" %>
    </div>
  <% end %>
</div>

app/views/schedules/index.erb
<%= render 'shared/header' %>
<div class='index-main'>

  <div class="calendar">
    <div class="calendar-header">
      <div id="prev-btn", class="prene-btn">←</div>
      <div class="month-y", id="month-year"></div>
      <div class="month-select"></div> <!-- プルダウンメニューの要素 -->
      <div id="next-btn", class="prene-btn">→</div>
    </div>
    <div class="day-header">
      <div class="day">Sun</div>
      <div class="day">Mon</div>
      <div class="day">Tue</div>
      <div class="day">Wed</div>
      <div class="day">Thu</div>
      <div class="day">Fri</div>
      <div class="day">Sat</div>
    </div>
    <div class="calendar-body">
      <!-- 日付部分 -->
    </div>
  </div>
  <div class="right_menu">
    <%= link_to "Write", new_schedule_path, class: "new feather-icon-container" %>
    <%= image_tag "feather.png", class:"feather-icon" %>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/schedules/index.html.erb
<!-- コンテンツ部分 -->
<div class='index'>
<%= render 'shared/loading' %>

  <div class="calendar tab-panels">
    <ul class="tabs">
      <li rel="panel-all", class="active", data-category-id="all">
        全体
      </li>
      <% @schedules = @schedules.sort_by { |schedule| schedule.category.id } %>
      <% displayed_category_ids = [] %>
      <% @schedules.each do |schedule| %>
        <% category_id = schedule.category.id %>
        <% if !displayed_category_ids.include?(category_id) %>
          <% displayed_category_ids << category_id %>
          <li rel="panel-<%= category_id %>" data-category-id="<%= category_id %>">
            <%= schedule.category.name %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <div class="calendar-main">
      <div class="calendar-header">
        <div id="prev-btn", class="prene-btn">←</div>
        <div class="month-y", id="month-year"></div>
        <div class="select-month"></div> <!-- プルダウンメニューの要素 -->
        <div id="next-btn", class="prene-btn">→</div>
      </div>
      <div class="day-header">
        <div class="day">Sun</div>
        <div class="day">Mon</div>
        <div class="day">Tue</div>
        <div class="day">Wed</div>
        <div class="day">Thu</div>
        <div class="day">Fri</div>
        <div class="day">Sat</div>
      </div>
      <div class="calendar-body">
        <!-- 日付部分 -->
      </div>
    </div>  
  </div>


  <div class="right_menu">
    <div class="new">
      <%= link_to "Write", new_schedule_path, class: "top-btn feather-icon-container" %>
    </div>
    <div class="list">
      <%= link_to "List.", index2_schedules_path, class: "top-btn feather-icon-container" %>
    </div>
  </div>
</div>

app/views/schedules/index2.html.erb
<%# CSS・・・assets/stylesheets/index2 %>

<div class='index' id="ind-sub">
  <div class='journal'>

    <div class="head-bj">
      <div class="title-bj">Bullet journal</div>
      <div class="select-month-ind2">
        <select>
          <option>----</option>
          <% @schedules_by_month.each do |month, schedules| %>
            <option value="#<%= month %>"><%= month %></option>
          <% end %>
        </select>
      </div>
    </div>

    <% @schedules_by_month.each do |month, schedules| %>
      <div class='main-bj'>
        <h4 class="date-month" id="<%= month %>"><%= month %></h4>
        <ul class="event-acbox">
            <% schedules.each do |s| %>
            <li class="acbox-items">
              <input id="ac-<%= s.id %>" type="checkbox" />
              <label for="ac-<%= s.id %>" class="fade-text to__bottom" style="--duration: 2.4s; --delay: 0.6s; --ease: ease-out">
                <div class="acbox-item">
                  <div class="date-item">
                    <% if s.description.present? %>
                      <div class="span1" style="cursor: pointer;">▽
                    <% else %>
                      <div class="span1">　
                    <% end %>
                        <%= s.start_time.strftime('%m/%d') %>
                        <% if s.end_time.present? %>
                           〜 
                        <% end %>
                        <%= s.end_time&.strftime('%m/%d') %>
                      </div>
                      <div class="span2">
                        cat: <%= s.category.name %>
                      </div>
                      <div class="span3">
                        <%= s.title %>
                      </div>
                  </div>
                  <div class="date-ed-de">
                    <%= link_to  "編集", edit_schedule_path(id: s.id), class: "event-edit" %>
                    <%= link_to  "削除", schedule_path(id: s.id), method: :delete, class: "event-delete" %>
                  </div>
                </div>
              </label>
              <% if s.description.present? %>
                <div class="acbox-under">
                  <%= s.description %>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="category">
    <div class="title-bj">Category list</div><br>
      <div class="new-form-cat">
        <%= form_with model: @category, local: true, class: 'category-form', id: "cat-form"  do |f| %>
          <%= f.hidden_field :id %>
          <%= f.text_field :name, class: "form-cat" %>
          <%= f.submit '+', class: 'cat-btn', id: "add-submit" %>
        <% end %>
      </div>
    <div class="category_list">
      <ul class="catlist">
        <% current_user.categories.each do |category| %>
          <li class="category-contents">
              <span><%= category.name %></span>
            <div class="cat-ed-de" id="<%= category.id %>">
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="button" id="scr-btn">↑</div>


<script>
$(function() {
  //セレクトボックススクロールの記述
  $('select').change(function () {
    // スクロールの速度
    const speed = 400; // ミリ秒
    const indSub = document.getElementById("ind-sub");
    const href = $(this).val(); // リンク先（value）を取得して、hrefという変数に代入
    const target = $(href == "#" || href == "" ? 'html' : href); // リンク先(href）のidがある要素を探して、targetに代入
    const position = target.offset().top; // idの要素の位置をoffset()で取得して、positionに代入
    indSub.scroll({
      top: position - 80,
      behavior: "smooth",
    });
  });

  //スクロールの記述
  const topBtn = document.getElementById("scr-btn");
  const indexSub = document.getElementById("ind-sub");

  topBtn.addEventListener("click", () => {
    indexSub.scroll({
      top: 0,
      behavior: "smooth",
    });
  });

  //削除アニメーションの記述
  $.fn.slideFadeToggle  = function(speed, easing, callback) {
      return this.animate({opacity: 'toggle', height: 'toggle'}, speed, easing, callback);
  };

  $('.category-contents').each(function() {
      const text = $(this).children('span').text();
      $(this).children('span').after($('<span />').text(text));
  });

  $('.category-contents .cat-ed-de').on('click', function(e) {
    // DELETEリクエストを送信
    const categoryId = $(this).attr('id'); // クリックされた要素のIDを取得
    const categoryElement = $(this).closest('.category-contents'); // .cat-ed-deの親要素である.category-contentsを取得
    // 削除の処理を実行
    $.ajax({
      url: '/categories/' + categoryId,
      type: 'DELETE',
      success: function() {
        // 成功時の処理（例: カテゴリを削除した後の画面更新など）
      },
      error: function() {
        // エラー時の処理
      }
    });

    $(this).addClass('active hover');
    const line = $('<div />').addClass('line');
    const li = $(this).parent();
    const span = $(this).parent().children('span:first-child');
    setTimeout(function() {
      li.append(line);
      line.css('right', li.width() - span.width() );
      line.animate({
        width: span.width() + 35
      }, 300, function() {
        li.addClass('beforeSlice');
        line.css({
          left: 0,
          right: 'auto'
        }).animate({
            width: 0
          }, 200, function() {
            li.addClass('slice');
            setTimeout(function() {
              li.slideFadeToggle(300, function() {
                li.remove();
              });
            }, 400);
          });
      });
    }, 200);
  });
});
</script>

app/views/schedules/index3.html.erb
<div class='index'>
  <div class="calendar">
    <ul class="tabs">
      <li rel="panel-all", class="active", data-category-id="all">
        全体
      </li>
      <% @schedules = @schedules.sort_by { |schedule| schedule.category.id } %>
      <% displayed_category_ids = [] %>
      <% @schedules.each do |schedule| %>
        <% category_id = schedule.category.id %>
        <% if !displayed_category_ids.include?(category_id) %>
          <% displayed_category_ids << category_id %>
          <li rel="panel-<%= category_id %>" data-category-id="<%= category_id %>">
            <%= schedule.category.name %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <div class="calendar-body">
      <div id='calendar'></div>
    </div>
  </div>
</div>

<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>
<script>
$('.tab-panels .tabs li').on('click', function () {
  // タブのアクティブクラスを切り替える処理
  $('.tab-panels .tabs .active').removeClass('active');
  $(this).addClass('active');
  // 選択されたカテゴリーIDを取得
  const paneltoshow = $(this).attr('rel');
  $('.tab-panels .calendar-panel.active').css('max-height', '100').slideUp('100', function () {
    $(this).removeClass('active');
    $('.' + paneltoshow).addClass('active').css('max-height', 'none').hide().slideDown('100');
  });
});


document.addEventListener('DOMContentLoaded', function () {
  var calendarEl = document.getElementById('calendar');
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const currentMonth = (currentDate.getMonth() + 1).toString().padStart(2, '0');
  const startYear = (currentYear - 2) + '-' + (currentMonth) + '-01'; // 表示する過去の年数
  const endYear = (currentYear + 1) + '-' + (currentMonth) + '-01'; // 表示する未来の年数

  var calendar = new FullCalendar.Calendar(calendarEl, {
    headerToolbar: {
      left: "prev today next",
      center: "title",
      right: "dayGridMonth,timeGridWeek,listWeek",
    },

    // 表示期間
    validRange: function () {
      return {
        start: startYear,
        end: endYear
      };
    },
    contentHeight: 650,
    dayMaxEvents: 2,
    navLinks: true,
    editable: true,
    // Ajaxでデータを取得して予定を表示
    events: function (info, successCallback, failureCallback) {
      $.ajax({
        url: '/schedules', // データを取得するURL
        type: 'GET',
        dataType: 'json',
        success: function (response) {
          // レスポンスを処理するコード
          const events = [];
          for (let i = 0; i < response.length; i++) {
            const schedule = response[i];
            //start_time
            const startDateTime = new Date(schedule.start_time);
            const startYear = startDateTime.getFullYear();
            const startMonth = startDateTime.getMonth() + 1;
            const startDay = startDateTime.getDate();
            const startKey = `${startYear}-${String(startMonth).padStart(2, '0')}-${String(startDay).padStart(2, '0')}`;
            //end_time
            const endDateTime = new Date(schedule.end_time);
            const endYear = endDateTime.getFullYear();
            const endMonth = endDateTime.getMonth() + 1;
            const endDay = endDateTime.getDate();
            const EndKey = `${endYear}-${String(endMonth).padStart(2, '0')}-${String(endDay).padStart(2, '0')}`;
            const eventUrl = window.location.href.toString(); // クリックされたイベントのURLを取得
            // end_timeがある時とない時
            if (schedule.end_time) {
              const event = {
                id: schedule.id,                      // イベントのタイトル
                title: schedule.title,                // イベントのタイトル
                start: startKey,                      // イベントの開始日
                end: EndKey,                          // イベントの終了日
                url: `/schedules/${schedule.id}/edit`, // イベントの編集URL
                classNames: 'event-list'
              };
              events.push(event);
            } else {
              const event = {
                id: schedule.id,
                title: schedule.title,
                start: startKey,
                url: `/schedules/${schedule.id}/edit`,
                classNames: 'event-list'
              };
              events.push(event);
            }
          }
          successCallback(events); // イベントデータをカレンダーに渡す
        },
        error: function (xhr, status, error) {
          // エラーハンドリングのコード
          failureCallback(error); // エラー時の処理
        }
      });
    }
    // Ajaxでデータを取得して予定を表示     ここまで



  });
  calendar.render();
});

</script>

app/views/schedules/new.erb
<%= render 'shared/header' %>

<div class="new-main">
  <%= form_with model: @schedule, class: "schedule-form", local: true, id: "schedule-form" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.date_field :start_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :end_time %>
      <%= f.date_field :end_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Write", class: "btn-write" %>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/schedules/new.html.erb
<div class="new-main">
  <%= image_tag "form-up.png", class: "form-flame" %>
  <%= form_with model: @schedule, class: "schedule-form", local: true, id: "schedule-form" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :start_time, class: "form-label" %>
      <%= f.date_field :start_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :end_time, class: "form-label" %>
      <%= f.date_field :end_time, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :category_id, class: "form-label" %>
      <%= link_to "追加", index2_schedules_path, class: "form-add" %>
      <%= f.collection_select :category_id, @categories, :id, :name, { include_blank: '---' }, { class: "form-select" } %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Write", class: "btn-write" %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
      <ul>
        <% model.errors.full_messages.each do |message| %>
          <li class='error-message'><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# CSS・・・assets/stylesheets/shared/footer.css %>

<div class='footer'>
  <div class='footer-contents'>
    <%= link_to 'chroniquillについて', "#", class: "footer-link" %>
  </div>
  <div class='footer-sign'>
    © Chroniquill
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>

<header class='top-page-header'>
  <div class='header-right'>
    <%= image_tag "header-title.png", class:"title-icon" %>
    <div class='top-title'>
    <%= link_to 'Chroniquil', root_path, class:"t-title" %>
    </div>
  </div>
  <% if user_signed_in? %>
  <div class='top-logout'>
    <%= link_to 'Close the Chroniquil', destroy_user_session_path, method: :delete, class: "logout" %>
  </div>
  <% else %>
  <% end %>
</header>

app/views/shared/_loading.html.erb
<!-- ローディング画面 -->
<div id="loading">
  <div class="spinner"></div>
</div>